export class CarsService {
  private cars = [
    {
      id : 1,
      carName: 'Honda CRV',
      carYear: '2013',
      carImagePath: '../../assets/images/HomePageBackround.jpg',
      carTrips: 217,
       carPrice: 38,
       description: 'A note on over-mileage:  I am absolutely willing to work with you on miles.  I give good discounts for over-mileage to good renters who upload the required photos and follow the directions, and inform me about the overmileage  Just ask me!  Thanks' ,
       features: 'Good sound system (no aux jack though).  Get out those old CDs!  Nice for long trips as well as errands and it lives for Ikea runs.  Has 2 12V outlets and I have included a 5v USB charger in the front',
       parkingDetails: 'Parked on the street at 128 Morris st.  Park on the street, NOT in the lot.  Even though SF is not easy, where it is parked in SOMA there are spots on morris most days day in the afternoon and evenings are no problem at all.  The only exception is Monday night because of street sweeping',
       guidelines: 'I do remote key handoff.  I will require your drivers license and photo per Turo terms - https://support.turo.com/hc/en-us/articles/115001847347-How-do-remote-key-handoffs-work-  Also I ask that you photograph the odometer before and after your trip and let me know if you went over mileage.  I am flexible with mileage but we have to discuss it first.  I keep my prices low this way.  Thanks!',
       dailyDistance: 80,
       weeklyDistance: 550,
       monthlyDistance:1500,
       ownerName: 'Mr. Sapte',
       milage: '24 MPG' ,
       fuelType: 'Gas(Premium)' ,
       doorCount: '4',
       seatCount: '4',

    },
    {
      id : 2,
      carName: 'Honda CRV',
      carYear: '2014',
      carImagePath: '../../assets/images/HomePageBackround.jpg',
      carTrips: 317,
      carPrice: 34,
      description: 'A note on over-mileage:  I am absolutely willing to work with you on miles.  I give good discounts for over-mileage to good renters who upload the required photos and follow the directions, and inform me about the overmileage  Just ask me!  Thanks' ,
      features: 'Good sound system (no aux jack though).  Get out those old CDs!  Nice for long trips as well as errands and it lives for Ikea runs.  Has 2 12V outlets and I have included a 5v USB charger in the front',
      parkingDetails: 'Parked on the street at 128 Morris st.  Park on the street, NOT in the lot.  Even though SF is not easy, where it is parked in SOMA there are spots on morris most days day in the afternoon and evenings are no problem at all.  The only exception is Monday night because of street sweeping',
      guidelines: 'I do remote key handoff.  I will require your drivers license and photo per Turo terms - https://support.turo.com/hc/en-us/articles/115001847347-How-do-remote-key-handoffs-work-  Also I ask that you photograph the odometer before and after your trip and let me know if you went over mileage.  I am flexible with mileage but we have to discuss it first.  I keep my prices low this way.  Thanks!',
      dailyDistance: 80,
      weeklyDistance: 550,
      monthlyDistance:1500,
      ownerName: 'Mr. Sapte',
      milage: '24 MPG' ,
      fuelType: 'Gas(Premium)' ,
      doorCount: '4',
      seatCount: '4',
    },
    {
      id : 3,
      carName: 'Lamborgini',
      carYear: '2004',
      carImagePath: '../../assets/images/HomePageBackround.jpg',
      carTrips: 315,
      carPrice: 54,
      description: 'A note on over-mileage:  I am absolutely willing to work with you on miles.  I give good discounts for over-mileage to good renters who upload the required photos and follow the directions, and inform me about the overmileage  Just ask me!  Thanks' ,
      features: 'Good sound system (no aux jack though).  Get out those old CDs!  Nice for long trips as well as errands and it lives for Ikea runs.  Has 2 12V outlets and I have included a 5v USB charger in the front',
      parkingDetails: 'Parked on the street at 128 Morris st.  Park on the street, NOT in the lot.  Even though SF is not easy, where it is parked in SOMA there are spots on morris most days day in the afternoon and evenings are no problem at all.  The only exception is Monday night because of street sweeping',
      guidelines: 'I do remote key handoff.  I will require your drivers license and photo per Turo terms - https://support.turo.com/hc/en-us/articles/115001847347-How-do-remote-key-handoffs-work-  Also I ask that you photograph the odometer before and after your trip and let me know if you went over mileage.  I am flexible with mileage but we have to discuss it first.  I keep my prices low this way.  Thanks!',
      dailyDistance: 80,
      weeklyDistance: 550,
      monthlyDistance:1500,
      ownerName: 'Mr. Sapte',
      milage: '24 MPG' ,
      fuelType: 'Gas(Premium)' ,
      doorCount: '4',
      seatCount: '4',
    },
    {
      id : 3,
      carName: 'Lamborgini',
      carYear: '2004',
      carImagePath: '../../assets/images/HomePageBackround.jpg',
      carTrips: 315,
      carPrice: 54,
      description: 'A note on over-mileage:  I am absolutely willing to work with you on miles.  I give good discounts for over-mileage to good renters who upload the required photos and follow the directions, and inform me about the overmileage  Just ask me!  Thanks' ,
      features: 'Good sound system (no aux jack though).  Get out those old CDs!  Nice for long trips as well as errands and it lives for Ikea runs.  Has 2 12V outlets and I have included a 5v USB charger in the front',
      parkingDetails: 'Parked on the street at 128 Morris st.  Park on the street, NOT in the lot.  Even though SF is not easy, where it is parked in SOMA there are spots on morris most days day in the afternoon and evenings are no problem at all.  The only exception is Monday night because of street sweeping',
      guidelines: 'I do remote key handoff.  I will require your drivers license and photo per Turo terms - https://support.turo.com/hc/en-us/articles/115001847347-How-do-remote-key-handoffs-work-  Also I ask that you photograph the odometer before and after your trip and let me know if you went over mileage.  I am flexible with mileage but we have to discuss it first.  I keep my prices low this way.  Thanks!',
      dailyDistance: 80,
      weeklyDistance: 550,
      monthlyDistance:1500,
      ownerName: 'Mr. Sapte',
      milage: '24 MPG' ,
      fuelType: 'Gas(Premium)' ,
      doorCount: '4',
      seatCount: '4',
    },
    {
      id : 3,
      carName: 'Lamborgini',
      carYear: '2004',
      carImagePath: '../../assets/images/car.jpg',
      carTrips: 315,
      carPrice: 80,
      description: 'A note on over-mileage:  I am absolutely willing to work with you on miles.  I give good discounts for over-mileage to good renters who upload the required photos and follow the directions, and inform me about the overmileage  Just ask me!  Thanks' ,
      features: 'Good sound system (no aux jack though).  Get out those old CDs!  Nice for long trips as well as errands and it lives for Ikea runs.  Has 2 12V outlets and I have included a 5v USB charger in the front',
      parkingDetails: 'Parked on the street at 128 Morris st.  Park on the street, NOT in the lot.  Even though SF is not easy, where it is parked in SOMA there are spots on morris most days day in the afternoon and evenings are no problem at all.  The only exception is Monday night because of street sweeping',
      guidelines: 'I do remote key handoff.  I will require your drivers license and photo per Turo terms - https://support.turo.com/hc/en-us/articles/115001847347-How-do-remote-key-handoffs-work-  Also I ask that you photograph the odometer before and after your trip and let me know if you went over mileage.  I am flexible with mileage but we have to discuss it first.  I keep my prices low this way.  Thanks!',
      dailyDistance: 80,
      weeklyDistance: 550,
      monthlyDistance:1500,
      ownerName: 'Mr. Sapte',
      milage: '24 MPG' ,
      fuelType: 'Gas(Premium)' ,
      doorCount: '4',
      seatCount: '4',
    },
    {
      id : 3,
      carName: 'Lamborgini',
      carYear: '2004',
      carImagePath: '../../assets/images/HomePageBackround.jpg',
      carTrips: 315,
      carPrice: 64,
      description: 'A note on over-mileage:  I am absolutely willing to work with you on miles.  I give good discounts for over-mileage to good renters who upload the required photos and follow the directions, and inform me about the overmileage  Just ask me!  Thanks' ,
      features: 'Good sound system (no aux jack though).  Get out those old CDs!  Nice for long trips as well as errands and it lives for Ikea runs.  Has 2 12V outlets and I have included a 5v USB charger in the front',
      parkingDetails: 'Parked on the street at 128 Morris st.  Park on the street, NOT in the lot.  Even though SF is not easy, where it is parked in SOMA there are spots on morris most days day in the afternoon and evenings are no problem at all.  The only exception is Monday night because of street sweeping',
      guidelines: 'I do remote key handoff.  I will require your drivers license and photo per Turo terms - https://support.turo.com/hc/en-us/articles/115001847347-How-do-remote-key-handoffs-work-  Also I ask that you photograph the odometer before and after your trip and let me know if you went over mileage.  I am flexible with mileage but we have to discuss it first.  I keep my prices low this way.  Thanks!',
      dailyDistance: 80,
      weeklyDistance: 550,
      monthlyDistance:1500,
      ownerName: 'Mr. Sapte',
      milage: '24 MPG' ,
      fuelType: 'Gas(Premium)' ,
      doorCount: '4',
      seatCount: '4',
    },
    {
      id : 3,
      carName: 'Lamborgini',
      carYear: '2004',
      carImagePath: '../../assets/images/HomePageBackround.jpg',
      carTrips: 315,
      carPrice: 84,
      description: 'A note on over-mileage:  I am absolutely willing to work with you on miles.  I give good discounts for over-mileage to good renters who upload the required photos and follow the directions, and inform me about the overmileage  Just ask me!  Thanks' ,
      features: 'Good sound system (no aux jack though).  Get out those old CDs!  Nice for long trips as well as errands and it lives for Ikea runs.  Has 2 12V outlets and I have included a 5v USB charger in the front',
      parkingDetails: 'Parked on the street at 128 Morris st.  Park on the street, NOT in the lot.  Even though SF is not easy, where it is parked in SOMA there are spots on morris most days day in the afternoon and evenings are no problem at all.  The only exception is Monday night because of street sweeping',
      guidelines: 'I do remote key handoff.  I will require your drivers license and photo per Turo terms - https://support.turo.com/hc/en-us/articles/115001847347-How-do-remote-key-handoffs-work-  Also I ask that you photograph the odometer before and after your trip and let me know if you went over mileage.  I am flexible with mileage but we have to discuss it first.  I keep my prices low this way.  Thanks!',
      dailyDistance: 80,
      weeklyDistance: 550,
      monthlyDistance:1500,
      ownerName: 'Mr. Sapte',
      milage: '24 MPG' ,
      fuelType: 'Gas(Premium)' ,
      doorCount: '4',
      seatCount: '4',
    }
  ];
  getCars() {
    return this.cars;
  }
  getCar(id: Number) {
    const car = this.cars.find(
      (c) => {
        return c.id === id;
      }
    );
    return car;
  }
}
